project:
  type: website 
  output-dir: docs

website:
  title: "MY_Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: SHAOHAN CV.pdf
        text: CV

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

